export * as alignChild from './alignChild';
export * as alignSelf from './alignSelf';
export * as baseComponent from './baseComponent';
export * as effect from './effect';
export * as mediaQuery from './mediaQuery';
export { default as pallete } from './pallete';
export { default as size } from './size';
export * as styling from './styling';
export * as typo from './typo';
export { default as zIndex } from './zIndex';
export * as values from '../values';
export { default as pad } from './pad';
export { default as spacing } from './spacing';
export { default as round } from './round';
